### ISSUE TITLE
Neural network-based programs can do better

### ISSUE THREAD

**Issue by KOLANICH** [jankrepl/pychubby#12]
https://github.com/SummitKwan/transparent_latent_gan
https://github.com/NVlabs/stylegan

I guess it should be mentioned in readme.

**Comment by jankrepl** [comment]
Hey @KOLANICH, thank you for your interest.

`pychubby` is purely based on geometric transformations (warping) of the input image. It cannot create new textures, objects, etc. So just from this point of you it is fundamentally different from pix2pix GANs and similar.

See below some comments on the two links:

**Transparent Latent GAN**

- You are not able to **provide your own input image**. You can just sample some latent `z` and then pass it through the (pretrained) generator. Changing the expressions/appearance is then just simply done via perturbing the latent `z` in the correct direction.

- The number of actions is limited by the attributes the feature extractor network was trained on [Dataset Celebrities](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html)

**Style GAN**
This is a brilliant paper however again I would like to point out that the goal of it is fundamentally different from `pychubby`.

- Same as for the first link, you are not able to **provide your own input image**. 

I would be more than happy to discuss further if you want to!
Cheers

**Comment by KOLANICH** [comment]
>pychubby is purely based on geometric transformations (warping) of the input image.

Yeah, I know. Just mean that since the results look unnatural the users may want to use the state of the art approaches giving better results.

**Comment by KOLANICH** [comment]
>You are not able to provide your own input image. You can just sample some latent z and then pass it through the (pretrained) generator. Changing the expressions/appearance is then just simply done via perturbing the latent z in the correct direction.

Isn' that net a half of an autoencoder, so if we had an encoder, it should be possible to create a latent vector corresponding to the image? Anyway, even if it isn't, restoring the latent vector corresponding to the image with backprop should work, though not as efficient, as if we had an encoder.

**Comment by jankrepl** [comment]
So the StyleGAN only contains the "decoder" path - the generator. Assuming that one wants to use their pretrained model then the only possibility left is finding `z` such that `G(z) ~ x`. As you pointed out it can be done through backprop and in general it is not clear whether such`z` even exists. Sure, one can just hope that we are close enough but I wonder what artifacts it is going to create.

I actually did some research and found one project that tries to achieve something very similar https://github.com/Puzer/stylegan-encoder. Its great and commend the author, however, let me point out a few problems:

- Requires gpus
- Not very user friendly (no setup.py -> not on PYPI + requires some background in ML). It's a fork of the official StyleGAN so I understand there are inherent limitations
- Only provides 3 latent directions (smile, age and gender)
- Aligns the original face and then only works with the aligned version of the image. That means that additional logic for changing the initial image would have to be implemented + logic for multiple faces
-  I haven't tested it but I would guess that in some cases it creates artifacts that are either due to imperfections in the pretratined model, encoding approximation (x -> z) or the latent space interpolations. For all of these there is no quick fix.
